### ISSUE TITLE
Edição da Ovitrampa

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#10]
Na página de visualização da ovitrampa, deve ser possível Ações 
- [x] Adicionar cartão
- [x] Editar dados cadastrais
- [x] Arquivar/desativar
- [x] Remover

**Comment by odascatolini** [comment]
@vgeorge ok, concluído, mas lembrando que antes de abrirmos o app para o piloto teremos que ocultar algumas opções que estão somente para testes, vou criar issue especifica para isso
