### ISSUE TITLE
Guia de montagem da armadilha

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#16]

**Comment by odascatolini** [comment]
@vgeorge 

Segue o tutorial

Creio que você já tenha as fotos separadas

As fotos com telas do app deverão ser substituídas quando tivermos a versão final no app

O ícone de alerta pode ser substituido por um do conjunto usado no app

[tutorial-construcao-armadilha-app.pptx](https://github.com/aetrapp/mobile/files/1920397/tutorial-construcao-armadilha-app.pptx)

**Comment by vgeorge** [comment]
No menu guias, alterar título para "Como construir uma armadilha"

**Comment by odascatolini** [comment]
@vgeorge 

Favor trocar os passos 20 e 23, são dois alertas, desculpe mas estavam invertidos no arquivo que enviei

**Comment by odascatolini** [comment]
@vgeorge

Segue tutorial atualizado com as telas do app atual.

Nesse mudaram os passos 46,47 e 48

Foto 46:

![tutorial-construcao-armadilha 046](https://user-images.githubusercontent.com/15959483/39086179-3d0c215c-4564-11e8-86f0-8d14a6f91833.jpg)

Texto 46:

Utilizando o aplicativo AeTrapp, clique em “Armadilhas" no menu inferior

Foto 47:

![tutorial-construcao-armadilha 047](https://user-images.githubusercontent.com/15959483/39086181-3ed03186-4564-11e8-8137-122b8ddf1b87.jpg)

Texto 47:

Clique no símbolo “+”, no canto superior direito, para cadastrar sua armadilha

Foto 48:

![tutorial-construcao-armadilha 048](https://user-images.githubusercontent.com/15959483/39086182-4304463e-4564-11e8-87c2-7a66a7ddcc02.jpg)

Texto 48:

Fotografe sua armadilha no local onde foi instalada, preencha todos os dados requeridos e clique em confirmar: sua armadilha está cadastrada no sistema!

Agora aguarde uma semana para fotografar a primeira amostra, você será notificado para não se esquecer

Muitas vezes não encontramos ovos nas duas primeiras semanas. Isso é normal, não desanime!

**Comment by odascatolini** [comment]
@vgeorge 

Não se esqueça:

Favor trocar os passos 20 e 23, são dois alertas, desculpe mas estavam invertidos no arquivo que enviei

**Comment by odascatolini** [comment]
@vgeorge 

As imagens estão ok

No meu celular, nos passos 45, 49 e 50 o texto é cortado

No menu guias, alterar título para "Como construir uma armadilha"

E aquele lance de deslizar para trás e andar para frente continua, mas isso pode ser resolvido depois.

Valeu

**Comment by vgeorge** [comment]
Está voltando para atrás agora. Tentei acomodar os textos, mas vai ser preciso reduzir os mais longos.

**Comment by odascatolini** [comment]
@vgeorge Não tem como reduzir os textos, estão iguais no site e videos. Teria como possibilitar scroll?

**Comment by odascatolini** [comment]
ok
