### ISSUE TITLE
Guia de coleta de cartão

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#17]

**Comment by odascatolini** [comment]
@vgeorge

Segue o tutorial

Creio que você já tenha as fotos separadas

As fotos com telas do app deverão ser substituídas quando tivermos a versão final no app

O ícone de alerta pode ser substituido por um do conjunto usado no app

[tutorial-fotografia-amostra-app.pptx](https://github.com/aetrapp/mobile/files/1920415/tutorial-fotografia-amostra-app.pptx)

**Comment by vgeorge** [comment]
O botão no índice deve ter o título "Como fotografar uma amostra".

**Comment by odascatolini** [comment]
@vgeorge 

Segue tutorial atualizado com as telas do app atual.

Nesse mudou somente o passo 11

Foto:
![tutorial-fotografias-amostras 011](https://user-images.githubusercontent.com/15959483/39086142-b723a650-4563-11e8-90b4-5b3462266b30.jpg)

Texto:

Abra o aplicativo AeTrapp, encontre sua armadilha no menu Armadilhas e clique no ícone da câmera fotográfica

**Comment by odascatolini** [comment]
@vgeorge 

Ok, só falta resolver a volta para o slide anterior

**Comment by vgeorge** [comment]
Alterado, por favor, verificar.

**Comment by odascatolini** [comment]
ok
