### ISSUE TITLE
Remoção do limite de armadilhas

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#25]
O usuário poderá ter quantas armadilhas necessitar e o botão "Iniciar armadilha em novo endereço" deve sempre aparecer

**Comment by odascatolini** [comment]
@vgeorge concluido. Como faço para mudar o label da issue para concluída? Não aparece essa opção aqui

**Comment by vgeorge** [comment]
@odascatolini A conclusão não é marcada via label, é um status geral da issue. No waffle você deve clicar no balão de comentários, no final aparece "Close issue". Via site do Github é só clicar no botão de mesmo nome.
