### ISSUE TITLE
Situação da armadilha

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#26]
Em “Situação”, trocar “Coletando ovos” por “Aguardando primeira amostra”, “Sem ovos”, “Abaixo da média do município”, “Na média do município”, “Acima da média do município”, “Amostra atrasada”, “Desativada”. Manter esse campo acima de última contagem.

**Comment by odascatolini** [comment]
@vgeorge essa está difícil de testar, toda vez que logo no app as armadilhas voltam para "Descarte e inicie o ciclo", quando faço isso muda para "Aguardando primeira amostra", mesmo depois que mando uma foto. Se aguardo o dia seguinte para olhar de novo, após teoricamente completar a janela, volta a situação "Descarte e inicie o ciclo"

**Comment by odascatolini** [comment]
ok
