### ISSUE TITLE
Remover campos do detalhe da amostra

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#35]
Creio que “Duração total” e “Concluída há"  não sejam informações relevantes para o colaborador. Podem ser excluídos da versão final, ou melhor, ocultados e revelados por meio de um botão para mais informações, mas mantida para os testes

**Comment by vgeorge** [comment]
@odascatolini Essa é uma issue antiga, parece-me que está contemplada.

**Comment by odascatolini** [comment]
ok
