### ISSUE TITLE
Alterações no detalhe da armadilha

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#36]
- [x] Trocar “Coleta feita em” por “Data”
- [x] Inserir "ID amostra” após “Número de ovos” e “Data” (ex: ID amostra B1P3eHdz). Mas lembrar que esse ID deve ser numérico
- [x] Ao clicar em "Visualizar imagem", garantir exibição no modo retrato, e não paisagem
- [x] Trocar “Situação" por “Resultado” na 2a imagem. Depois do erro, pode ter um link em destaque: “Ver tutorial novamente"
- [x] Na 1a imagem, adicionar “Situação”: “Sem ovos”, “Abaixo da média do município”, “Na média do município”, “Acima da média do município”, com referência à média municipal no momento da coleta. Colocar na primeira linha, acima de contagem (Número de ovos) 
- [x] Observe na 2a imagem acima que há um pequeno mapa com a localização da armadilha e a cor do pin é relacionada à situação: “Sem ovos”, “Abaixo da média do município”, “Na média do município”, “Acima da média do município”. Temos essa opção ou a proposta dos círculos coloridos na próxima página.

**Comment by vgeorge** [comment]
Sobre a situação da armadilha, no topo ficou se ela está ativa/desativada/vencida/pronta. A situação da contagem ficou mais abaixo como neste exemplo:

![screenshot_1521745648](https://user-images.githubusercontent.com/329694/37792688-58f5c278-2e04-11e8-82f5-525e6fdbfe49.png)

**Comment by odascatolini** [comment]
@vgeorge 

1- Passar o gráfico para a página de amostras;

2- É melhor fundir o campo "Relação à média" com "Situação", deixando somente o "Situação" lá em cima, contendo: Aguardando 1a amostra / Desativada / Amostra atrasada (em vermelho se possível) / Última amostra inválida / Abaixo da média da cidade / Na média da cidade / Acima da média da cidade

3- Remover:
- Iniciar novo ciclo de amostra
- Apagar armadilha

Sugiro a seguinte ordem nos campos:

ID armadilha
Situação
Média da Cidade

**Local**
(endereço)

**Última amostra**
Número de ovos
Data

**Ações**
Fotografar amostra
Ver armadilha (imagem da armadilha)
Desativar armadilha

**Comment by odascatolini** [comment]
@vgeorge 

Parece tudo ok, mas tenho que esperar mais um dia pois reativei a armadilha, enviei amostra e continuo vendo a situação "aguardando amostra", já que desativei e reativei, reiniciando o ciclo. Amanhã estando tudo ok fecho a thread.

Só um ajuste, ao clicar em Ver imagem da armadilha, a foto aparece em modo paisagem (com a armadilha deitada), não estando de acordo com a orientação original

**Comment by vgeorge** [comment]
A questão da orientação foi colocada na issue https://github.com/aetrapp/mobile/issues/56. Vou fechar esta issue e reabriremos em caso de necessidade.
