### ISSUE TITLE
Histórico da armadilha

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#37]
<img width="238" alt="image" src="https://user-images.githubusercontent.com/329694/36731335-58fa3e88-1bc2-11e8-8a15-ed7175ec3988.png">

Essa tela é a mesma rascunhada nas especificações como “Histórico da Ovitrampa” (2a imagem acima)
Trocar o ID da amostra na lista pela data e quantidade de ovos, como na imagem da direita. O ID aparecerá na tela “Detalhes da amostra"
Colocar ao lado de cada linha, após a quantidade de ovos, um ícone (um círculo colorido?) com o código de cores referente às categorias “Sem ovos”, “Abaixo da média do município”, “Na média do município”, “Acima da média do município”. Talvez pudesse ser algo assim também, com o número de ovos dentro do circulo:
      
Ao clicar nas linhas, abrir a tela “Detalhes da amostra”

**Comment by odascatolini** [comment]
@vgeorge O gráfico está legal, mas difícil leitura para o público em geral. Sugerimos simplificar o layout para linhas, como na proposta abaixo:

![grafico-aetrapp](https://user-images.githubusercontent.com/15959483/38364604-b77c74e4-38af-11e8-9faa-8c352469d7ae.jpg)

**Comment by vgeorge** [comment]
@odascatolini 

Vou corrigir o alinhamento do título e legenda. 

Sobre o tipo de gráfico, fiz a contagem como barras porque esta é uma série que não é uniforme e contínua, como a média das cidades. Pode ser que o intervalo entre contagem seja maior ou menor que sete dias devido a atrasos ou que não haja contagem em uma semana. Se for utilizada linha pode parecer que há informação válida para um período em quem não há.

**Comment by vgeorge** [comment]
Alterei o alinhamento do título e legenda.

**Comment by odascatolini** [comment]
@vgeorge tudo ok obrigado
