### ISSUE TITLE
Ids pronunciáveis

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#39]
O gerador de ids agora usa os seguintes caracteres:

```
23456789ABCDEFGHJKLMNPQRSTUVWXYZ
```

Não constam os caracteres `OI0L` porque são muitos parecidos e, dependendo da fonte, podem gerar confusão.

O comprimento do id é de 13 caracteres, o que gera a seguinte probabilidade de colisão:

<img width="808" alt="captura de tela 2018-03-23 as 11 39 30" src="https://user-images.githubusercontent.com/329694/37827358-0a1b3cb0-2e8f-11e8-860a-ae78a3107752.png">

https://alex7kom.github.io/nano-nanoid-cc/

**Comment by odascatolini** [comment]
ok @vgeorge concluido
