### ISSUE TITLE
Mensagem de erro em "Detalhes da amostra"

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/mobile#41]
@vgeorge A mensagem de erro sai cortada quando o texto é grande, ex: "A imagem apresenta sombras ......"

**Comment by odascatolini** [comment]
@vgeorge , as telas estão ok, e tudo bem que não dá para colocar o "carregando".

Quanto às mensagens, gostaria de perguntar se existe algum problema em ficarem um pouco mais longas. A idéia seria além do erro, dar orientações para a sua correção, e talvez um link para o tutorial no app. Você dando o ok eu reformulo aqui os textos.

**Comment by vgeorge** [comment]
@odascatolini Tudo bem, pode ser um texto maior.

**Comment by odascatolini** [comment]
@vgeorge , seguem os textos, mas ainda estou aguardando resposta do João para editar o erro 8.

Peço por favor que ajuste as fontes se necessário para não ficar tão grande, talvez com a mesma fonte que usou no endereço de armadilha fique bom.

ERR_001$A imagem ficou desfocada ou com baixa qualidade. 
Fotografe novamente com o celular bem apoiado para não tremer, em local com boa iluminação natural, conforme o tutorial. Toque a borda azul do círculo antes de fotografar para que a paleta fique em foco, e envie novamente.
ERR_002$Imagem muito escura.
Procure um lugar com boa iluminação natural, seguindo as orientações do tutorial. Fotografe e envie novamente.
ERR_003$Não foi possível detectar o círculo central. 
Pode ser que o círculo não foi desenhado corretamente, não ficou completamente fechado ou não foi desenhado com caneta esferográfica azul e desbotou. Nesse caso, higienize a armadilha, substitua a paleta e envie nova amostra na próxima semana.
ERR_004$A imagem apresenta sombras ou alguma outra coisa que possa atrapalhar o reconhecimento dos ovos. 
Procure um lugar com boa iluminação natural, verifique se não há sombras do celular ou de outros objetos na paleta. Fotografe e envie novamente, seguindo as orientações do tutorial.
ERR_005$Bordas da paleta não encontradas. 
Verifique se a fotografia foi tomada conforme o tutorial, com a câmera o mais próximo possível da paleta mas sem cortar as bordas. Fotografe e envie novamente.
ERR_006$Bordas da paleta e círculo central não encontrados. 
Verifique se a fotografia foi tomada conforme o tutorial, com a câmera o mais próximo possível da paleta mas sem cortar as bordas. Fotografe e envie novamente. Caso a paleta não tenha sido desenhada com caneta esferográfica azul, higienize a armadilha, troque a paleta e envie nova amostra na próxima semana.
ERR_007$A paleta parece estar molhada. 
A água gera reflexos que dificultam a contagem dos ovos. Aguarde a paleta secar, fotografe conforme o tutorial e envie novamente.
ERR_008$Imagem com baixa resolução. 
O AeTrapp necessita de imagens com resolução mínima de XX x XX pixels. Verifique nas configurações de seu celular se a resolução está configurada corretamente. Caso seu celular não alcance essa resolução mínima, você precisará de um outro aparelho para realizar o monitoramento.
ERR_009$Paleta não reconhecida. 
Verifique se a foto enviada é realmente a foto de uma paleta e se foi tirada sobre um fundo branco. Revise os tutoriais se necessário. Caso sua paleta não tenha sido feita corretamente, higienize a armadilha, troque a paleta e envie nova amostra na próxima semana.
ERR_010$Enquadramento da paleta inadequado.
Verifique se a fotografia foi tomada conforme o tutorial, com a câmera o mais próximo possível da paleta mas sem cortar as bordas. Fotografe e envie novamente.

**Comment by odascatolini** [comment]
@vgeorge Editei com a resolução mínima, textos ok agora

**Comment by vgeorge** [comment]
Adicionei as mensagens, que podem ser revisadas aqui:

https://github.com/aetrapp/mobile/blob/master/src/screens/samples/Show.js#L96-L121

Agora o app exibe as instruções para correção:

![simulator screen shot - iphone 6 - 2018-07-16 at 14 02 00](https://user-images.githubusercontent.com/329694/42772601-52e31cc0-8901-11e8-8974-5b304c6d5127.png)

**Comment by odascatolini** [comment]
ok
