### ISSUE TITLE
Notificações

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/mobile#42]
@vgeorge é urgente a implementação das notificações de fotografia para o usuário

**Comment by vgeorge** [comment]
Foram implementadas as seguintes notificações dos seguintes eventos:

- "Uma coleta está próxima", exibida 1 dia antes do início da janela de coleta;
- "Uma coleta está pronta", exibida no início da janela de coleta;
- "Análise de amostra concluída", exibida ao fim de uma análise de amostra.

**Comment by odascatolini** [comment]
@vgeorge 

"Análise de amostra concluída" está ok. Quanto às outras:

Trocar o texto "Uma coleta está próxima" por:

**Amanhã é dia de fotografar amostra!**
Não se esqueça, amanhã você deve fotografar a amostra de sua armadilha no endereço <endereço>

Trocar o texto "Uma coleta está pronta" por:

**Hoje é dia de fotografar amostra!** 

Não se esqueça, hoje é dia de fotografar a amostra, trocar a paleta e higienizar sua armadilha no endereço <endereço>. Veja o tutorial com as orientações (link para o tutorial nessa ultima frase)

.E nos dias subsequentes, caso não seja enviada fotografia e caso o usuário não tenha desativado a armadilha, deve receber diariamente a mensagem, até que envie nova foto ou desative a armadilha:

**Atenção!** (em vermelho)
Você não realizou a manutenção semanal de sua armadilha no endereço <endereço>. Envie hoje a fotografia da amostra. Se quiser interromper temporariamente o monitoramento, desative sua armadilha no aplicativo e guarde ou descarte corretamente o material. Para voltar a monitorar no futuro, basta reativá-la no app. Não deixe sua armadilha se transformar em um criadouro!"

Obs 1: favor colocar uma opção para o usuário deletar uma notificação

Obs 2: falta ainda receber as notificações push

**Comment by vgeorge** [comment]
Os textos foram revisados.

Sobre os **avisos de armadilhas vencidas*,* serão feitas sete notificações (1 semana) após o fim da janela. Apesar de mais complexa, podem ser implementadas a geração indefinida de notificações, mas me pareceu suficiente avisar por uma semana se há a salvaguarda do moderador em avaliar e contactar os responsáveis por armadilhas atrasadas.

Sobre as **notificações push**, por favor, façam o seguinte teste: enviem uma nova amostra para avaliação ou reavalie uma amostra já enviada e coloque o app em background. Deve aparecer uma notificação push assim que a análise for concluída. Todos os eventos da armadilha e amostra devem aparecer com push agora. 

Ainda há uma questão a ser resolvida que é o a abertura da tela correspondente (amostra ou armadilha) quando a notificação push é clicada. Atualmente o deeplink (link para página interna do app) só funciona de dentro do app. 

Sobre a opção de deletar notificação, coloquei em um issue em separado: https://github.com/aetrapp/mobile/issues/46

**Comment by odascatolini** [comment]
@vgeorge 

Quanto à notificações por 7 dias, ok;

Recebi a notificação push de análise concluída. Quanto às de "amanhã é dia" e de "hoje é dia", é melhor estabelecer um horário padrão para o envio (não sei se você fez isso já), poderia ser às 8h00 am, pois se a armadilha for cadastrada à noite o colaborador só receberá à noite;

Quanto à revisão dos textos, na mensagem push está ok, mas na tela de notificações continua com o texto antigo

**Comment by vgeorge** [comment]
@odascatolini 

Na próxima versão as notificações futuras serão agendadas às 08:00 do horário de Brasília. Verifiquei a geração dos textos na tela de notificações do app e estão corretos. Pode ser que você esteja vendo os antigos, mas os gerados a partir do último deploy devem estar ok. Se persistir o problema abriremos uma issue para tratar da correção.

**Comment by odascatolini** [comment]
@vgeorge ok, mas ainda não recebi a notificação de armadilha vencida

**Comment by odascatolini** [comment]
@vgeorge 

Ok, notificação de armadilha vencida recebida e textos alterados na tela de notificações
