### ISSUE TITLE
Icone

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/mobile#44]
@vgeorge Favor especificar o formato e tamanho dos arquivos para o ícone da aplicação, e substituir o nome de "AETrapp" para "AeTrapp"

**Comment by vgeorge** [comment]
Existe um gerador automático de ícones que podemos usar para a atualização. É necessário um arquivo de ícone em formato quadrado, em .png ou .psd, com resolução maior do que 192x192 px. 

Sobre a correção de nome vamos acompanhar na issue #45.

**Comment by vgeorge** [comment]
Aqui está a documentação do gerador:

https://github.com/bamlab/generator-rn-toolbox/tree/master/generators/assets#generate-splashscreens

**Comment by odascatolini** [comment]
@vgeorge serve esse?
![icone](https://user-images.githubusercontent.com/15959483/38367472-2e684368-38b9-11e8-9e4a-1247e7bc523b.png)

**Comment by vgeorge** [comment]
Tentei rodar aqui, mas o script não aceita porque esta imagem não é quadrada.

**Comment by odascatolini** [comment]
@vgeorge agora está quadrada:

![icone-android](https://user-images.githubusercontent.com/15959483/38558120-8d0bd57a-3ca5-11e8-98b4-178b54cfd817.png)

**Comment by odascatolini** [comment]
@vgeorge aguardando próxima versão do app com o novo ícone para validar

**Comment by odascatolini** [comment]
ok
