### ISSUE TITLE
Ciclo de amostra

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/mobile#47]
@vgeorge conforme conversamos, veja se assim está ok:

A amostra deverá ser enviada no 7o dia mas será aceita até o 8o dia. Caso não seja enviada amostra, deve mudar de status e cor no 8o dia.

- Quando a amostra for aceita, o colaborador será notificado:
Amostra analisada com sucesso! Realize a manutenção de sua armadilha corretamente (limpeza do recipiente, troca do capim e da paleta). Vamos continuar monitorando?
Sim, iniciar novo ciclo de coleta
Não, desativar armadilha temporariamente

Caso clique em sim, o ciclo reinicia na data atual e o usuário passa a receber notificações dentro de 6 dias.

Caso desative temporariamente, será notificado após 3 e 7 dias:

Você desativou sua temporariamente sua armadilha no endereço XXXXX. Gostaria de reativá-la e voltar a contribuir com o AeTrapp? Você pode reativá-la a qualquer momento no menu Armadilhas.
Sim, reativar armadilha agora e iniciar novo ciclo de coleta
Agora não, manter armadilha desativada

**Comment by vgeorge** [comment]
Também alterar o ciclo para 7 dias.

A sugestão de reabertura foi movida para https://github.com/aetrapp/mobile/issues/57.

**Comment by vgeorge** [comment]
Parece-me que esta issue está concluída, há alguma questão pendente que não tratamos em outra?

**Comment by odascatolini** [comment]
@vgeorge 

Olhando agora essa mensagem:

Amostra analisada com sucesso! Realize a manutenção de sua armadilha corretamente (limpeza do recipiente, troca do capim e da paleta). Vamos continuar monitorando?
Sim, iniciar novo ciclo de coleta
Não, desativar armadilha temporariamente

Você não acha que ela é mais clara do que a que está lá atualmente?

Tem que ter uma mensagem alternativa para quando a amostra não foi realizada com sucesso. Fica essa sugestão (avalie e faça os ajustes que achar necessários nessas mensagens):

Amostra não reconhecida: [erro]
Fotografe e envie novamente conforme o tutorial.
Caso o sistema não a reconheça novamente, é provável que a amostra esteja deteriorada.
Nesse caso, descarte essa amostra e realize a manutenção de sua armadilha corretamente (limpeza do recipiente, troca do capim e da paleta) para a próxima semana. Vamos continuar monitorando?
Sim, iniciar novo ciclo de coleta
Não, desativar armadilha temporariamente

**Comment by odascatolini** [comment]
@vgeorge 

Outra coisa, como conversamos por Skype, peço por gentileza que faça uma explicação de como ficou a lógica no final, da maneira que achar melhor (texto, fluxograma), para que toda a equipe fique ciente e possa orientar os usuários. Favor compartilhar isso com o Caio.

**Comment by vgeorge** [comment]
Adicionei a explicação sobre o ciclo de coleta no README. @cscheidegger 

As mensagem estão assim agora:

## Amostra analisada com sucesso!
Uma amostra válida foi recebida e agora é preciso iniciar novo ciclo ou desativar a armadilha, escolhendo uma opção na seção "Ações".

## Ciclo em atraso!
Envie uma amostra válida, inicie um novo ciclo ou desative a armadilha.

**Comment by odascatolini** [comment]
ok

**Comment by cscheidegger** [comment]
Valeu Vitor,

Abraços !
