### ISSUE TITLE
Ajustes interface/visual

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/mobile#49]
@vgeorge 

Conforme conversamos, seguem ajustes visuais para o app:

- Substituição do ícone;

- Substituição dos pins no mapa:

![pin-blue](https://user-images.githubusercontent.com/15959483/38632259-8c439d38-3d92-11e8-9465-ebbcd1e3b21a.png)

- Ícone de câmera fotográfica em "Fotografar amostra" para dar mais destaque;

- Opção mapa/satelite e botões de zoom no mapa;

- Tooltip nas armadilhas

Seguem telas do app antigo que podem servir de referencia:

![app-rio-branco](https://user-images.githubusercontent.com/15959483/38632336-cb3afe1e-3d92-11e8-8129-d31c5fd60bae.jpeg)

**Comment by vgeorge** [comment]
Aqui a mudança foi a colocação das cores das armadilhas a partir do novo processo de cálculo de status. As armadilhas anteriores irão aparecer vermelhas, mas após reativá-las serão exibidas as cores respectivas. As outras alterações estão pendentes.

**Comment by odascatolini** [comment]
@vgeorge vou fotografar amostras com números diferentes de ovos e esperar a mudança de status amanhã para ver como fica e validar

**Comment by vgeorge** [comment]
Desmembrar em outros issues.

**Comment by vgeorge** [comment]
Os dois últimos itens foram desmembrados em https://github.com/aetrapp/mobile/issues/63 e https://github.com/aetrapp/mobile/issues/62, o restante foi resolvido.

**Comment by odascatolini** [comment]
ok
