### ISSUE TITLE
Tutorial no app

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/mobile#50]
@vgeorge 

Favor especificar como devem ser entregues as imagens para os dois tutoriais no app (armadilha e fotografia). Segue sugestão de layout (draft):

![tutorial-app](https://user-images.githubusercontent.com/15959483/38632854-577f962c-3d94-11e8-8cd1-42e2e13be71b.jpeg)

**Comment by vgeorge** [comment]
Estou usando imagens quadradas de 600px. Existem duas issues abertas referentes a cada um dos guias, lá podemos tratar de questões específicas:

* Montagem: https://github.com/aetrapp/mobile/issues/16
* Coleta: https://github.com/aetrapp/mobile/issues/17

**Comment by vgeorge** [comment]
As questões deste issue que não foram deslocadas para outros issues estão resolvidas.

**Comment by odascatolini** [comment]
ok
