### ISSUE TITLE
Montar "cenário" para demonstração

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/mobile#55]
@vgeorge 

Conforme conversamos precisamos montar um "cenário" para demonstração do app em algum município com armadilhas, amostras e média municipal.

Vou cadastrar 5 armadilhas em algum município aleatório, com amostras, e te aviso para mudar as datas das amostras no banco.

**Comment by vgeorge** [comment]
Remover as armadilhas antigas que estão aparecendo incorretamente e adicionar armadilhas em João Pessoa ou outra cidade.

**Comment by odascatolini** [comment]
@vgeorge 

Segue link para arquivo com 15 fotos de amostras para compor o cenário. Pode ser em João Pessoa - PB mesmo. Vou precisar do login dos usuários para demonstrar.

https://drive.google.com/open?id=1vbJR8KtB7-qV9Z-UOGbZdtA5m2k9eHmd
