### ISSUE TITLE
Exibir a média da cidade até o momento atual

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#58]
Para evitar que seja exibida uma parte "vazia", o gráfico deve utilizar a mesma média da última semana até o dia atual.

**Comment by vgeorge** [comment]
Acho que faltou o registro aqui, mas lembro que testamos uma linha que "extende" a média até o dias atuais e ficou confuso. Atualmente está assim, me parece que está ok:

![screenshot_1531351377](https://user-images.githubusercontent.com/329694/42604399-ea30df5c-8548-11e8-911d-f936b64e065d.png)

**Comment by odascatolini** [comment]
ok
