### ISSUE TITLE
Lista de amostras da armadilha

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#6]
A lista de cartões de uma ovitrampa deve ser acessível via tela de ovitrampa. 

- [x] Exibição da listagem

**Comment by vgeorge** [comment]
Mudando o status desta issue, a lista foi revisada e o gráfico podemos acompanhar na issue https://github.com/aetrapp/mobile/issues/12.

**Comment by odascatolini** [comment]
@vgeorge 

1- amostras em ordem decrescente ok;
2- o gráfico deve estar nessa página, no topo, não na de "Informações da armadilha";
3- favor substituir o texto "Acione um item paras ver detalhes" por um ícone de seta à direita em cada linha de amostra, padronizando com as outras páginas

**Comment by odascatolini** [comment]
@vgeorge tudo ok obrigado
