### ISSUE TITLE
Tooltip nas armadilhas

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#63]
![image](https://user-images.githubusercontent.com/329694/39068071-68e6b002-44b1-11e8-92ba-a4ee7d652c96.png)

**Comment by vgeorge** [comment]
Implementado. Ao clicar no marcador, o mapa é centralizado e o tooltip é exibido com as seguintes informações:

- Endereço (título)
- Identificador
- Situação
- Número de amostras enviadas
- Última contagem de ovos e data (se houver)

Ao acionar o tooltip o usuário é levado à página com detalhes da armadilha.

**Comment by odascatolini** [comment]
ok
