### ISSUE TITLE
Atualização da interface após edição de objetos (realtime)

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#64]
Após um chamado bem sucedido de edição via API é preciso atualizar o store. Em alguns casos não está sendo feito, como na criação da armadilha. 

Também é preciso que o cliente "assine" notificações de edição via channels do feathers, o que depende da resolução de https://github.com/aetrapp/api/issues/52.

**Comment by vgeorge** [comment]
Implantado. Para testar, edite o endereço de uma armadilha de teste no dashboard e veja se ela se altera automaticamente no app. É preciso estar na versão 0.0.27.

**Comment by odascatolini** [comment]
ok
