### ISSUE TITLE
Amostra foi fotografada mas status da armadilha ficou "atrasada"

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/mobile#68]
@vgeorge 

A armadilha PHGD65LNUPHME teve amostra analisada com sucesso mas o status ficou atrasada

**Comment by vgeorge** [comment]
Problema similar à https://github.com/aetrapp/webapp/issues/49.

Resolução depende da issue https://github.com/aetrapp/mobile/issues/70.

**Comment by odascatolini** [comment]
Assunto urgente

**Comment by vgeorge** [comment]
Conforme conversamos, novo comportamento do app faz com que o usuário tenha que iniciar novo ciclo deliberadamente, como descrito na issue https://github.com/aetrapp/mobile/issues/70.

**Comment by odascatolini** [comment]
@vgeorge ok, sugiro corrigir a mensagem que aparece truncada, fazer o mais rápido possível o upload da nova versão para a Play Store e explicar a mudança para que o Caio comunique os colaboradores.
