### ISSUE TITLE
Notificações não estão sendo enviadas

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/mobile#69]
@vgeorge 

O Marcelo tem uma armadilha cuja data de fotografia é hoje, mas não recebeu notificações nem ontem nem hoje, esse é um problema mais sério/urgente

**Comment by odascatolini** [comment]
@vgeorge 

Testei enviar para usuários com armadilhas em João Pessoa e para meu usuário específico.

Recebi ambas notificações instantaneamente, porém:

- Ao clicar na notificação no Android, o app abre na tela de armadilhas, não de notificações;

- Na tela de notificações não consigo ver a notificação recebida. Provavelmente uma questão de paginação, pois minha tela está lotada de notificações, não tenho como apagá-las, e elas ainda aparecem fora de ordem de data.

**Comment by vgeorge** [comment]
Se estiver ok, sugiro o fechamento desta issue. Há issues abertas para os pontos em que você lenvantou no último comentário:

- Exibir mensagem do broadcast na notificação #71
- Deeplink nas notificações #72
- Apagar notificação #46

**Comment by odascatolini** [comment]
@vgeorge ok, fechando aqui
