### ISSUE TITLE
Visualização de cartão

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#7]
O usuário deverá poder visualizar em uma tela os detalhes de um cartão e realizar ações sobre ele.

Detalhes:
- [x] Visualização da imagem em resolução original
- [x] Contagem de ovos, se houver
- [x] Erros de processamento, se houver

Ações:
- [x] Reanalizar imagem
- [x] Interromper análise
- [x] Remover cartão

**Comment by odascatolini** [comment]
@vgeorge ok, concluído, mas lembrando que antes de abrirmos o app para o piloto teremos que ocultar algumas opções que estão somente para testes, vou criar issue especifica para isso
