### ISSUE TITLE
Botão e notificação de inicio novo ciclo

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#70]
Após o usuário enviar uma amostra válida e o IPS retornar o seu resultado, a armadilha passa a ter a propriedade `cycleIsFinished` igual a `true`, indicando que o ciclo terminou e agora é necessária ação de iniciar novo ciclo ou desativação da armadilha. 

Um botão "Iniciar novo ciclo" deve ser exibido na tela da armadilha, além do botão de desativação, que já é exibido. Sempre que a tela é aberta, é exibida uma notificação de que o ciclo se encerrou e usuário deve realizar uma das seguintes ações:

- Enviar amostra válida (se já já enviou a mensagem é ligeramente diferente);
- Iniciar novo ciclo;
- Desativar armadilha.

**Comment by odascatolini** [comment]
@vgeorge Complicado isso no meio do piloto

**Comment by odascatolini** [comment]
@vgeorge a mensagem está aparecendo, mas aparece cortada, tem uma parte que não dá para ler

**Comment by odascatolini** [comment]
ok
