### ISSUE TITLE
Exibir mensagem do broadcast na notificação

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#71]
Está aparecendo apenas o título.

**Comment by vgeorge** [comment]
A interface e comportamento das notificações foi alterado. Quando o usuário receber um broadcast, esta é a sequência de passos para abri-lo no app:

## Notificação é recebida, apenas o título é exibido

![screenshot_1528292879](https://user-images.githubusercontent.com/329694/41042271-98f09c50-6977-11e8-8116-70824c1486fd.png)

## Ao clicá-la, usuário é direcionado para a tela da notificação

![screenshot_1528292887](https://user-images.githubusercontent.com/329694/41042306-b0f91494-6977-11e8-80c6-75df629ac8ce.png)

## Ao voltar, é exibida a lista de notificações ao usuário

![screenshot_1528292891](https://user-images.githubusercontent.com/329694/41042333-c463d816-6977-11e8-83c8-7abe1b7b119e.png)

**Comment by odascatolini** [comment]
ok
