### ISSUE TITLE
Deeplink nas notificações

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/mobile#72]
Verificar se é possível que notificação abra a tela alvo (armadilhas, amostras, notificações).

**Comment by vgeorge** [comment]
Implementado. Quando o usuário clica no aviso de notificação no sistema, é aberta uma tela com detalhes da notificação, ao invés de abrir diretamente a armadilha/amostra. Exemplos:

![screenshot_1528292533](https://user-images.githubusercontent.com/329694/41041773-64f16764-6976-11e8-815c-0dbb466e0efe.png)

![screenshot_1528292537](https://user-images.githubusercontent.com/329694/41041778-68fc10ac-6976-11e8-826e-5326dbd0cec6.png)

**Comment by odascatolini** [comment]
ok
