### ISSUE TITLE
Amostra vencida

### ISSUE THREAD

**Issue by cscheidegger** [aetrapp/mobile#73]
Usuária submeteu amostra no dia 3/5 
No dia 4/5 recebeu notificação de armadilha desativada ou vencida. 
Pergunta como proceder 

![whatsapp image 2018-06-04 at 17 27 04](https://user-images.githubusercontent.com/39593264/40993156-337f5a3a-68cf-11e8-8bb3-0a57e61e9c18.jpeg)
![whatsapp image 2018-06-05 at 14 37 58](https://user-images.githubusercontent.com/39593264/40993158-33a462a8-68cf-11e8-92fa-94c3db95dbc9.jpeg)
![whatsapp image 2018-06-04 at 10 11 59](https://user-images.githubusercontent.com/39593264/40993159-33c5cf56-68cf-11e8-9131-953e8fd9c4a6.jpeg)

**Comment by vgeorge** [comment]
Oi Caio, parece que ela está utilizando uma versão mais antiga do app. Ao atualizar o app para a útima versão disponível (v0.0.24), ela poderá iniciar novo ciclo na tela de armadilha.

**Comment by cscheidegger** [comment]
Valeu Vitor ,

Pedi para o pessoal atualizar

Em 5 de jun de 2018 4:12 PM, "Vitor George" <notifications@github.com>
escreveu:

Oi Caio, parece que ela está utilizando uma versão mais antiga do app. Ao
atualizar o app para a útima versão disponível (v0.0.24), ela poderá
iniciar novo ciclo na tela de armadilha.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aetrapp/mobile/issues/73#issuecomment-394826830>, or mute
the thread
