### ISSUE TITLE
Desativação automática de armadilhas atrasadas

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/mobile#74]
@vgeorge

No 10o dia do ciclo, a armadilha atrasada deve ser desativada e o usuário deve receber a seguinte notificação:

Sua armadilha completou 10 dias sem manutenção e está sendo desativada. Descarte a armadilha corretamente ou higienize e guarde-a para reutilizar no futuro. Ela poderá ser reinstalada e reativada a qualquer momento no app.

**Comment by odascatolini** [comment]
@vgeorge 

No 10o dia do ciclo, a armadilha atrasada deve ser desativada e o usuário deve receber a seguinte notificação:

Sua armadilha completou 10 dias sem manutenção e está sendo desativada. Descarte a armadilha corretamente ou higienize e guarde-a para reutilizar no futuro. Ela poderá ser reinstalada e reativada a qualquer momento no app.

**Comment by vgeorge** [comment]
Foi implantando um job que verificar a cada 5 minutos armadilhas abandonada e enviar notificações avisando a desativação automática.

**Comment by odascatolini** [comment]
ok
